/*
 * Заказ на ресурсы облака
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class CloudsApiController : ControllerBase
    { 
        /// <summary>
        /// Метод отмены заказа на облако по ID
        /// </summary>
        /// <param name="cloudId">Идентификатор заказа облака</param>
        /// <response code="200">Успешный ответ заказом облака по ID</response>
        /// <response code="404">Not Found</response>
        /// <response code="500">Internal Server Error</response>
        /// <response code="0">Все остальное</response>
        [HttpDelete]
        [Route("/clouds/{cloud_id}")]
        [ValidateModelState]
        [SwaggerOperation("CencelCloudById")]
        [SwaggerResponse(statusCode: 404, type: typeof(Error404), description: "Not Found")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error500), description: "Internal Server Error")]
        [SwaggerResponse(statusCode: 0, type: typeof(Error), description: "Все остальное")]
        public virtual IActionResult CencelCloudById([FromRoute][Required]string cloudId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(Error404));

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default(Error500));

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0, default(Error));

            throw new NotImplementedException();
        }

        /// <summary>
        /// Метод создания заказа на облако
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Успешный ответ на создание заказа облака</response>
        /// <response code="404">Not Found</response>
        /// <response code="500">Internal Server Error</response>
        /// <response code="0">Все остальное</response>
        [HttpPost]
        [Route("/clouds")]
        [ValidateModelState]
        [SwaggerOperation("CreateCloud")]
        [SwaggerResponse(statusCode: 200, type: typeof(Cloud), description: "Успешный ответ на создание заказа облака")]
        [SwaggerResponse(statusCode: 404, type: typeof(Error404), description: "Not Found")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error500), description: "Internal Server Error")]
        [SwaggerResponse(statusCode: 0, type: typeof(Error), description: "Все остальное")]
        public virtual IActionResult CreateCloud([FromBody]Error body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Cloud));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(Error404));

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default(Error500));

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0, default(Error));
            string exampleJson = null;
            exampleJson = "{\n  \"OS\" : \"Windows\",\n  \"id_client\" : \"f102b615\",\n  \"cloud_id\" : \"f102b615\",\n  \"RAM\" : \"128\"\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Cloud>(exampleJson)
                        : default(Cloud);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Метод получения списка ресурсов на облако ID
        /// </summary>
        /// <param name="cloudId">Идентификатор заказа облака</param>
        /// <response code="200">Успешный ответ с заказом облака по ID</response>
        /// <response code="404">Not Found</response>
        /// <response code="500">Internal Server Error</response>
        /// <response code="0">Все остальное</response>
        [HttpGet]
        [Route("/clouds/{cloud_id}")]
        [ValidateModelState]
        [SwaggerOperation("GetAllCloudById")]
        [SwaggerResponse(statusCode: 200, type: typeof(Cloud), description: "Успешный ответ с заказом облака по ID")]
        [SwaggerResponse(statusCode: 404, type: typeof(Error404), description: "Not Found")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error500), description: "Internal Server Error")]
        [SwaggerResponse(statusCode: 0, type: typeof(Error), description: "Все остальное")]
        public virtual IActionResult GetAllCloudById([FromRoute][Required]string cloudId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Cloud));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(Error404));

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default(Error500));

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0, default(Error));
            string exampleJson = null;
            exampleJson = "{\n  \"OS\" : \"Windows\",\n  \"id_client\" : \"f102b615\",\n  \"cloud_id\" : \"f102b615\",\n  \"RAM\" : \"128\"\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Cloud>(exampleJson)
                        : default(Cloud);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Метод получения списка ресурсов на облако
        /// </summary>
        /// <param name="cloudId">Идентификатор заказа облака</param>
        /// <response code="200">Успешный ответ со списком ресурсов в облаке</response>
        /// <response code="404">Not Found</response>
        /// <response code="500">Internal Server Error</response>
        /// <response code="0">Все остальное</response>
        [HttpGet]
        [Route("/clouds")]
        [ValidateModelState]
        [SwaggerOperation("GetAllClouds")]
        [SwaggerResponse(statusCode: 200, type: typeof(Resurces), description: "Успешный ответ со списком ресурсов в облаке")]
        [SwaggerResponse(statusCode: 404, type: typeof(Error404), description: "Not Found")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error500), description: "Internal Server Error")]
        [SwaggerResponse(statusCode: 0, type: typeof(Error), description: "Все остальное")]
        public virtual IActionResult GetAllClouds([FromRoute][Required]string cloudId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Resurces));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(Error404));

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default(Error500));

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0, default(Error));
            string exampleJson = null;
            exampleJson = "{\n  \"OS\" : \"Windows\",\n  \"HDD\" : \"1024\",\n  \"CPU\" : \"16\",\n  \"RAM\" : \"128\"\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Resurces>(exampleJson)
                        : default(Resurces);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
